export const watches = [
    {
        frontImage: "../../assets/w1.avif",
        backImage: "../../assets/w11.avif",
        name: "Citizen Tsuyosa NJ0154-80H ",
        dial: "45 mm x 42.1 mm",
        crystal: "Sapphỉe",
        price: "$800",
        gender: "female",
    },
    {
        frontImage: "../../assets/w2.avif",
        backImage: "../../assets/w22.avif",
        name: "Casio World Time AE ",
        dial: "45 mm x 42.1 mm",
        crystal: "Sapphỉe",
        price: "$810",
        gender: "female",
    },
    {
        frontImage: "../../assets/w7.avif",
        backImage: "../../assets/w77.avif",
        name: "Citizen EX1538-50E",
        dial: "45 mm x 42.1 mm",
        crystal: "Sapphỉe",
        price: "$220",
        gender: "female",
    },
    {
        frontImage: "../../assets/w3.avif",
        backImage: "../../assets/w33.avif",
        name: "G-Shock GA ",
        dial: "45 mm x 42.1 mm",
        crystal: "Sapphỉe",
        price: "$400",
        gender: "male",
    },
    {
        frontImage: "../../assets/w4.avif",
        backImage: "../../assets/w44.avif",
        name: "Doxa Executive D217RIY ",
        dial: "45 mm x 42.1 mm",
        crystal: "Sapphỉe",
        price: "$800",
        gender: "male",
    },
    {
        frontImage: "../../assets/w5.avif",
        backImage: "../../assets/w55.avif",
        name: "Doxa Calex Spiral Heart D179SWH ",
        dial: "45 mm x 42.1 mm",
        crystal: "Sapphỉe",
        price: "$800",
        gender: "male",
    },
    {
        frontImage: "../../assets/w6.avif",
        backImage: "../../assets/w66.avif",
        name: "Fossil FS5933  ",
        dial: "45 mm x 42.1 mm",
        crystal: "Sapphỉe",
        price: "$500",
        gender: "male",
    },

    {
        frontImage: "../../assets/w8.avif",
        backImage: "../../assets/w88.avif",
        name: "Doxa GrandeMetre ",
        dial: "45 mm x 42.1 mm",
        crystal: "Sapphỉe",
        price: "$800",
        gender: "female",
    },
    {
        frontImage: "../../assets/w9.avif",
        backImage: "../../assets/w99.avif",
        name: "Longines Présence L4.821.4.11.6",
        dial: "45 mm x 42.1 mm",
        crystal: "Sapphỉe",
        price: "$1000",
        gender: "female",
    },
    {
        frontImage: "../../assets/w10.avif",
        backImage: "../../assets/w1010.avif",
        name: "Koi K001.436.642.29.01.01",
        dial: "45 mm x 42.1 mm",
        crystal: "Sapphỉe",
        price: "$900",
        gender: "male",
    },
];